export const GET_MUSIC_REQUEST = "GET_MUSIC_REQUEST";
export const GET_MUSIC_SUCCESS = "GET_MUSIC_SUCCESS";
export const GET_MUSIC_FAILURE = "GET_MUSIC_FAILURE";

export const UPLOAD_MUSIC_REQUEST = "UPLOAD_MUSIC_REQUEST";
export const UPLOAD_MUSIC_SUCCESS = "UPLOAD_MUSIC_SUCCESS";
export const UPLOAD_MUSIC_FAILURE = "UPLOAD_MUSIC_FAILURE";
export const UPLOAD_MUSIC_RESET = "UPLOAD_MUSIC_RESET";

export const EDIT_MUSIC_REQUEST = "EDIT_MUSIC_REQUEST";
export const EDIT_MUSIC_SUCCESS = "EDIT_MUSIC_SUCCESS";
export const EDIT_MUSIC_FAILURE = "EDIT_MUSIC_FAILURE";
export const EDIT_MUSIC_RESET = "EDIT_MUSIC_RESET";

export const GET_MUSIC_BY_ID_REQUEST = "GET_MUSIC_BY_ID_REQUEST";
export const GET_MUSIC_BY_ID_SUCCESS = "GET_MUSIC_BY_ID_SUCCESS";
export const GET_MUSIC_BY_ID_FAILURE = "GET_MUSIC_BY_ID_FAILURE";

export const DELETE_MUSIC_REQUEST = "DELETE_MUSIC_REQUEST";
export const DELETE_MUSIC_SUCCESS = "DELETE_MUSIC_SUCCESS";
export const DELETE_MUSIC_FAILURE = "DELETE_MUSIC_FAILURE";
export const DELETE_MUSIC_RESET = "DELETE_MUSIC_RESET";